// Auto-generated by LibreLane
module rosc_spi_bridge(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  input cio_sck_i,
  input cio_csb_i,
  input cio_sd_i,
  output cio_sd_o,
  input rosc_enable_i,
  input start_i,
  input stop_i
);
endmodule
