meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Render the layout after sealring insertion
    KLayout.Render: null
    +KLayout.SealRing: KLayout.Render

    # Save time during development
    # Enable for sign-off
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null
    
    Checker.YosysSynthChecks: null  # Fails due to multisources in PLL

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv

- dir::../otUSB/src/usb_wrapper.sv
- dir::../otUSB/src/prim_util/prim_util_pkg.sv
- dir::../otUSB/src/other_prim/prim_mubi_pkg.sv
- dir::../otUSB/src/other_prim/prim_buf.sv
- dir::../otUSB/src/other_prim/prim_clock_mux2.sv
- dir::../otUSB/src/other_prim/prim_intr_hw.sv
- dir::../otUSB/src/other_prim/prim_onehot_check.sv
- dir::../otUSB/src/other_prim/prim_xnor2.sv
- dir::../otUSB/src/other_prim/prim_reg_we_check.sv
- dir::../otUSB/src/prim_cdc/prim_cdc_rand_delay.sv
- dir::../otUSB/src/prim_flop/prim_flop.sv
- dir::../otUSB/src/prim_flop/prim_sparse_fsm_flop.sv
- dir::../otUSB/src/prim_flop/prim_flop_2sync.sv
- dir::../otUSB/src/prim_count/prim_count_pkg.sv
- dir::../otUSB/src/prim_count/prim_count.sv
- dir::../otUSB/src/prim_sec/prim_sec_anchor_buf.sv
- dir::../otUSB/src/prim_sec/prim_sec_anchor_flop.sv
- dir::../otUSB/src/other_prim/prim_diff_decode.sv
- dir::../otUSB/src/other_prim/prim_edge_detector.sv
- dir::../otUSB/src/other_prim/prim_filter.sv
- dir::../otUSB/src/prim_sync/prim_sync_reqack.sv
- dir::../otUSB/src/prim_sync/prim_pulse_sync.sv
- dir::../otUSB/src/prim_cdc/prim_reg_cdc_arb.sv
- dir::../otUSB/src/prim_cdc/prim_reg_cdc.sv
- dir::../otUSB/src/prim_fifo/prim_fifo_assert.svh
- dir::../otUSB/src/prim_fifo/prim_fifo_sync_cnt.sv
- dir::../otUSB/src/prim_fifo/prim_fifo_sync.sv
- dir::../otUSB/src/prim_subreg/prim_subreg_pkg.sv
- dir::../otUSB/src/prim_subreg/prim_subreg_ext.sv
- dir::../otUSB/src/prim_subreg/prim_subreg_arb.sv
- dir::../otUSB/src/prim_subreg/prim_subreg.sv
- dir::../otUSB/src/usb_consts_pkg.sv
- dir::../otUSB/src/usb_fs_nb_out_pe.sv
- dir::../otUSB/src/usb_fs_nb_in_pe.sv
- dir::../otUSB/src/usb_fs_rx.sv
- dir::../otUSB/src/usb_fs_tx.sv
- dir::../otUSB/src/usb_fs_tx_mux.sv
- dir::../otUSB/src/usb_fs_nb_pe.sv
- dir::../otUSB/src/usbdev_reg_pkg.sv
- dir::../otUSB/src/support_reg_hw_pkg.sv
- dir::../otUSB/src/usbdev_counter.sv
- dir::../otUSB/src/usbdev_linkstate.sv
- dir::../otUSB/src/usbdev_aon_wake.sv
- dir::../otUSB/src/usbdev_iomux.sv
- dir::../otUSB/src/usbdev_usbif.sv
- dir::../otUSB/src/bus_reg_pkg.sv
- dir::../otUSB/src/usbdev_reg_top.sv
- dir::../otUSB/src/usbdev.sv
 
VERILOG_INCLUDE_DIRS: [ dir::../caravel/verilog/ ]

# Enable plugin for better SystemVerilog support
USE_SLANG: True

# 3.3V CELL LIBRABRY
STD_CELL_LIBRARY: gf180mcu_as_sc_mcu7t3v3
STD_CELL_LIBRARY_OPT: gf180mcu_as_sc_mcu7t3v3

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__qrcode_id
- gf180mcu_ws_ip__shuttle_id
- gf180mcu_ws_ip__project_id
- gf180mcu_ws_ip__logo
- gf180mcu_ws_ip__marker
- usbdev

# Clock
CLOCK_NET: i_chip_core.wb_clk_buf/Y

CLOCK_PERIOD: 20 # 50 MHz

TIME_DERATING_CONSTRAINT: 7
CLOCK_UNCERTAINTY_CONSTRAINT: 0.1

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.7
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.7

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 35
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CFG: dir::pdn/pdn_cfg.tcl
PDN_CORE_RING: True
#PDN_CORE_VERTICAL_LAYER: Metal4
#PDN_CORE_HORIZONTAL_LAYER: Metal
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal4
PDN_CORE_HORIZONTAL_LAYER: Metal3
PDN_HPITCH: 50
PDN_CORE_RING_CONNECT_TO_PAD_LAYERS: [Metal2]

# To disable ports buffering & wire repair with dly cells as they degrade timing
#PNR_EXCLUDED_CELL_FILE: dir::../caravel/librelane/pnr_exclude.cells

RUN_POST_GRT_RESIZER_TIMING: True
GRT_RESIZER_HOLD_SLACK_MARGIN: 1.0
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_HOLD_MAX_BUFFER_PCT: 100
GRT_RESIZER_ALLOW_SETUP_VIOS: True

# To fix antennas
DESIGN_REPAIR_MAX_WIRE_LENGTH: 1000
#DIODE_ON_PORTS: both
GRT_ANTENNA_MARGIN: 20
GRT_ANTENNA_ITERS: 10
DRT_ANTENNA_REPAIR_ITERS: 10

# Do not error on magic DRC violations
# Note: Passing magic DRC is not required for the submission.
# However, it is recommended to fix or carefully review all violations.
#ERROR_ON_MAGIC_DRC: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

# Since we cannot meet the minimum density limit on Metal2,
# ignore active metal on previous and subsequent layers
# (DM.5_DM.7 and DM.4_DM.6). Dummy metal is moved to active
# metal during the precheck.
KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

# Image render settings
KLAYOUT_RENDER_RESOLUTION: 2048
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::gf180mcu_render.lyp

# DRC settings
# A high number of workers increases RAM usage,
# but can significantly improve the performance.
# workers * threads should equal the available
# hardware threads for a best possible utilization.

KLAYOUT_DRC_THREADS: 1

# "max" equals max hardware threads
KLAYOUT_DRC_OPTIONS:
  decks: "all,-antenna,-density,-cup" # disable CUP for now
  variant: ref::$PDK
  workers: max

KLAYOUT_DENSITY_OPTIONS:
  decks: "density"
  variant: ref::$PDK
  workers: max

KLAYOUT_ANTENNA_OPTIONS:
  decks: "antenna"
  variant: ref::$PDK
  workers: max
