// Auto-generated by LibreLane
module gf180_ram_1024x8_wrapper(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input CLK,
  input CEN,
  input GWEN,
  input[7:0] WEN,
  input[9:0] A,
  input[7:0] D,
  output[7:0] Q
);
endmodule
