// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package usbdev_reg_pkg;

  // Param list
  parameter int NEndpoints = 3;

  // Address widths within the block
  parameter int BlockAw = 12; //confirm address size

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } av_setup_empty;
    struct packed {
      logic        q;
    } link_out_err;
    struct packed {
      logic        q;
    } powered;
    struct packed {
      logic        q;
    } frame;
    struct packed {
      logic        q;
    } rx_bitstuff_err;
    struct packed {
      logic        q;
    } rx_pid_err;
    struct packed {
      logic        q;
    } rx_crc_err;
    struct packed {
      logic        q;
    } link_in_err;
    struct packed {
      logic        q;
    } av_overflow;
    struct packed {
      logic        q;
    } rx_full;
    struct packed {
      logic        q;
    } av_out_empty;
    struct packed {
      logic        q;
    } link_resume;
    struct packed {
      logic        q;
    } link_suspend;
    struct packed {
      logic        q;
    } link_reset;
    struct packed {
      logic        q;
    } host_lost;
    struct packed {
      logic        q;
    } disconnected;
    struct packed {
      logic        q;
    } pkt_sent;
    struct packed {
      logic        q;
    } pkt_received;
  } usbdev_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } av_setup_empty;
    struct packed {
      logic        q;
    } link_out_err;
    struct packed {
      logic        q;
    } powered;
    struct packed {
      logic        q;
    } frame;
    struct packed {
      logic        q;
    } rx_bitstuff_err;
    struct packed {
      logic        q;
    } rx_pid_err;
    struct packed {
      logic        q;
    } rx_crc_err;
    struct packed {
      logic        q;
    } link_in_err;
    struct packed {
      logic        q;
    } av_overflow;
    struct packed {
      logic        q;
    } rx_full;
    struct packed {
      logic        q;
    } av_out_empty;
    struct packed {
      logic        q;
    } link_resume;
    struct packed {
      logic        q;
    } link_suspend;
    struct packed {
      logic        q;
    } link_reset;
    struct packed {
      logic        q;
    } host_lost;
    struct packed {
      logic        q;
    } disconnected;
    struct packed {
      logic        q;
    } pkt_sent;
    struct packed {
      logic        q;
    } pkt_received;
  } usbdev_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } av_setup_empty;
    struct packed {
      logic        q;
      logic        qe;
    } link_out_err;
    struct packed {
      logic        q;
      logic        qe;
    } powered;
    struct packed {
      logic        q;
      logic        qe;
    } frame;
    struct packed {
      logic        q;
      logic        qe;
    } rx_bitstuff_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_pid_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_crc_err;
    struct packed {
      logic        q;
      logic        qe;
    } link_in_err;
    struct packed {
      logic        q;
      logic        qe;
    } av_overflow;
    struct packed {
      logic        q;
      logic        qe;
    } rx_full;
    struct packed {
      logic        q;
      logic        qe;
    } av_out_empty;
    struct packed {
      logic        q;
      logic        qe;
    } link_resume;
    struct packed {
      logic        q;
      logic        qe;
    } link_suspend;
    struct packed {
      logic        q;
      logic        qe;
    } link_reset;
    struct packed {
      logic        q;
      logic        qe;
    } host_lost;
    struct packed {
      logic        q;
      logic        qe;
    } disconnected;
    struct packed {
      logic        q;
      logic        qe;
    } pkt_sent;
    struct packed {
      logic        q;
      logic        qe;
    } pkt_received;
  } usbdev_reg2hw_intr_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } usbdev_reg2hw_alert_test_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } device_address;
    struct packed {
      logic        q;
      logic        qe;
    } resume_link_active;
    struct packed {
      logic        q;
    } enable;
  } usbdev_reg2hw_usbctrl_reg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_ep_out_enable_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_ep_in_enable_mreg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
  } usbdev_reg2hw_avoutbuffer_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
  } usbdev_reg2hw_avsetupbuffer_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
      logic        re;
    } ep;
    struct packed {
      logic        q;
      logic        re;
    } setup;
    struct packed {
      logic [6:0]  q;
      logic        re;
    } size;
    struct packed {
      logic [3:0]  q;
      logic        re;
    } buffer;
  } usbdev_reg2hw_rxfifo_reg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_rxenable_setup_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_rxenable_out_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_set_nak_out_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_in_sent_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_out_stall_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_in_stall_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } rdy;
    struct packed {
      logic        q;
    } pend;
    struct packed {
      logic [6:0]  q;
    } size;
    struct packed {
      logic [3:0]  q;
    } buffer;
  } usbdev_reg2hw_configin_mreg_t;

/*   typedef struct packed {
    logic        q;
  } usbdev_reg2hw_out_iso_mreg_t;

  typedef struct packed {
    logic        q;
  } usbdev_reg2hw_in_iso_mreg_t; */

  typedef struct packed {
    struct packed {
      logic [2:0] q;
      logic        qe;
    } mask;
    struct packed {
      logic [2:0] q;
      logic        qe;
    } status;
  } usbdev_reg2hw_out_data_toggle_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0] q;
      logic        qe;
    } mask;
    struct packed {
      logic [2:0] q;
      logic        qe;
    } status;
  } usbdev_reg2hw_in_data_toggle_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } en;
    struct packed {
      logic        q;
    } dn_pullup_en_o;
    struct packed {
      logic        q;
    } dp_pullup_en_o;
    struct packed {
      logic        q;
    } rx_enable_o;
    struct packed {
      logic        q;
    } oe_o;
    struct packed {
      logic        q;
    } se0_o;
    struct packed {
      logic        q;
    } d_o;
    struct packed {
      logic        q;
    } dn_o;
    struct packed {
      logic        q;
    } dp_o;
  } usbdev_reg2hw_phy_pins_drive_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } tx_osc_test_mode;
    struct packed {
      logic        q;
    } usb_ref_disable;
    struct packed {
      logic        q;
    } pinflip;
    struct packed {
      logic        q;
    } eop_single_bit;
    struct packed {
      logic        q;
    } tx_use_d_se0;
    struct packed {
      logic        q;
    } use_diff_rcvr;
  } usbdev_reg2hw_phy_config_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } wake_ack;
    struct packed {
      logic        q;
      logic        qe;
    } suspend_req;
  } usbdev_reg2hw_wake_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rx_rst;
    struct packed {
      logic        q;
      logic        qe;
    } avsetup_rst;
    struct packed {
      logic        q;
      logic        qe;
    } avout_rst;
  } usbdev_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rst;
    struct packed {//reduced from logic [11:0] q
      logic [2:0] q;
      logic        qe;
    } endpoints;
    struct packed {
      logic        q;
      logic        qe;
    } ign_avsetup;
    struct packed {
      logic        q;
      logic        qe;
    } drop_avout;
    struct packed {
      logic        q;
      logic        qe;
    } drop_rx;
    struct packed {
      logic        q;
      logic        qe;
    } datatog_out;
  } usbdev_reg2hw_count_out_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rst;
    struct packed {//reduced from logic [11:0] q
      logic [2:0] q;
      logic        qe;
    } endpoints;
    struct packed {
      logic        q;
      logic        qe;
    } timeout;
    struct packed {
      logic        q;
      logic        qe;
    } nak;
    struct packed {
      logic        q;
      logic        qe;
    } nodata;
  } usbdev_reg2hw_count_in_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rst;
    struct packed {//reduced from logic [11:0] q
      logic [2:0] q;
      logic        qe;
    } endpoints;
  } usbdev_reg2hw_count_nodata_in_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } rst;
    struct packed {
      logic        q;
      logic        qe;
    } crc5;
    struct packed {
      logic        q;
      logic        qe;
    } crc16;
    struct packed {
      logic        q;
      logic        qe;
    } bitstuff;
    struct packed {
      logic        q;
      logic        qe;
    } pid_invalid;
  } usbdev_reg2hw_count_errors_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } av_setup_empty;
    struct packed {
      logic        d;
      logic        de;
    } link_out_err;
    struct packed {
      logic        d;
      logic        de;
    } powered;
    struct packed {
      logic        d;
      logic        de;
    } frame;
    struct packed {
      logic        d;
      logic        de;
    } rx_bitstuff_err;
    struct packed {
      logic        d;
      logic        de;
    } rx_pid_err;
    struct packed {
      logic        d;
      logic        de;
    } rx_crc_err;
    struct packed {
      logic        d;
      logic        de;
    } link_in_err;
    struct packed {
      logic        d;
      logic        de;
    } av_overflow;
    struct packed {
      logic        d;
      logic        de;
    } rx_full;
    struct packed {
      logic        d;
      logic        de;
    } av_out_empty;
    struct packed {
      logic        d;
      logic        de;
    } link_resume;
    struct packed {
      logic        d;
      logic        de;
    } link_suspend;
    struct packed {
      logic        d;
      logic        de;
    } link_reset;
    struct packed {
      logic        d;
      logic        de;
    } host_lost;
    struct packed {
      logic        d;
      logic        de;
    } disconnected;
    struct packed {
      logic        d;
      logic        de;
    } pkt_sent;
    struct packed {
      logic        d;
      logic        de;
    } pkt_received;
  } usbdev_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  d;
      logic        de;
    } device_address;
  } usbdev_hw2reg_usbctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } rx_empty;
    struct packed {
      logic        d;
    } av_setup_full;
    struct packed {
      logic [3:0]  d;
    } rx_depth;
    struct packed {
      logic        d;
    } av_out_full;
    struct packed {
      logic [2:0]  d;
    } av_setup_depth;
    struct packed {
      logic [3:0]  d;
    } av_out_depth;
    struct packed {
      logic        d;
    } sense;
    struct packed {
      logic [2:0]  d;
    } link_state;
    struct packed {
      logic        d;
    } host_lost;
    struct packed {
      logic [10:0] d;
    } frame;
  } usbdev_hw2reg_usbstat_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } ep;
    struct packed {
      logic        d;
    } setup;
    struct packed {
      logic [6:0]  d;
    } size;
    struct packed {
      logic [3:0]  d;
    } buffer;
  } usbdev_hw2reg_rxfifo_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } usbdev_hw2reg_rxenable_out_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } usbdev_hw2reg_in_sent_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } usbdev_hw2reg_out_stall_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } usbdev_hw2reg_in_stall_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } rdy;
    struct packed {
      logic        d;
      logic        de;
    } pend;
    struct packed {
      logic        d;
      logic        de;
    } sending;
  } usbdev_hw2reg_configin_mreg_t;

//reduced from logic [11:0] q
  typedef struct packed {
    struct packed {
      logic [2:0] d;
    } mask;
    struct packed {
      logic [2:0] d;
    } status;
  } usbdev_hw2reg_out_data_toggle_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0] d;
    } mask;
    struct packed {
      logic [2:0] d;
    } status;
  } usbdev_hw2reg_in_data_toggle_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } pwr_sense;
    struct packed {
      logic        d;
    } tx_oe_o;
    struct packed {
      logic        d;
    } tx_se0_o;
    struct packed {
      logic        d;
    } tx_d_o;
    struct packed {
      logic        d;
    } tx_dn_o;
    struct packed {
      logic        d;
    } tx_dp_o;
    struct packed {
      logic        d;
    } rx_d_i;
    struct packed {
      logic        d;
    } rx_dn_i;
    struct packed {
      logic        d;
    } rx_dp_i;
  } usbdev_hw2reg_phy_pins_sense_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } bus_not_idle;
    struct packed {
      logic        d;
      logic        de;
    } bus_reset;
    struct packed {
      logic        d;
      logic        de;
    } disconnected;
    struct packed {
      logic        d;
      logic        de;
    } module_active;
  } usbdev_hw2reg_wake_events_reg_t;

  typedef struct packed {
    struct packed {//reduced from logic [11:0] q
      logic [2:0] d;
    } endpoints;
    struct packed {
      logic        d;
    } ign_avsetup;
    struct packed {
      logic        d;
    } drop_avout;
    struct packed {
      logic        d;
    } drop_rx;
    struct packed {
      logic        d;
    } datatog_out;
    struct packed {
      logic [7:0]  d;
    } count;
  } usbdev_hw2reg_count_out_reg_t;

  typedef struct packed {
    struct packed {//reduced from logic [11:0] q 
      logic [2:0] d;
    } endpoints;
    struct packed {
      logic        d;
    } timeout;
    struct packed {
      logic        d;
    } nak;
    struct packed {
      logic        d;
    } nodata;
    struct packed {
      logic [7:0]  d;
    } count;
  } usbdev_hw2reg_count_in_reg_t;

  typedef struct packed {
    struct packed {//reduced from logic [11:0] q
      logic [2:0] d;
    } endpoints;
    struct packed {
      logic [7:0]  d;
    } count;
  } usbdev_hw2reg_count_nodata_in_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } crc5;
    struct packed {
      logic        d;
    } crc16;
    struct packed {
      logic        d;
    } bitstuff;
    struct packed {
      logic        d;
    } pid_invalid;
    struct packed {
      logic [7:0]  d;
    } count;
  } usbdev_hw2reg_count_errors_reg_t;

  // Register -> HW type
  //reduced [11:0]
  typedef struct packed {
    usbdev_reg2hw_intr_state_reg_t intr_state; // [550:533]
    usbdev_reg2hw_intr_enable_reg_t intr_enable; // [532:515]
    usbdev_reg2hw_intr_test_reg_t intr_test; // [514:479]
    usbdev_reg2hw_usbctrl_reg_t usbctrl; // [476:467]
    usbdev_reg2hw_ep_out_enable_mreg_t ep_out_enable_0;
    usbdev_reg2hw_ep_out_enable_mreg_t ep_out_enable_1;
    usbdev_reg2hw_ep_out_enable_mreg_t ep_out_enable_2;
    usbdev_reg2hw_ep_in_enable_mreg_t ep_in_enable_0;
    usbdev_reg2hw_ep_in_enable_mreg_t ep_in_enable_1;
    usbdev_reg2hw_ep_in_enable_mreg_t ep_in_enable_2;
    usbdev_reg2hw_avoutbuffer_reg_t avoutbuffer; // [442:437]
    usbdev_reg2hw_avsetupbuffer_reg_t avsetupbuffer; // [436:431]
    usbdev_reg2hw_rxfifo_reg_t rxfifo; // [430:410]
    usbdev_reg2hw_rxenable_setup_mreg_t rxenable_setup_0;
    usbdev_reg2hw_rxenable_setup_mreg_t rxenable_setup_1;
    usbdev_reg2hw_rxenable_setup_mreg_t rxenable_setup_2;
    usbdev_reg2hw_rxenable_out_mreg_t rxenable_out_0;
    usbdev_reg2hw_rxenable_out_mreg_t rxenable_out_1;
    usbdev_reg2hw_rxenable_out_mreg_t rxenable_out_2;
    usbdev_reg2hw_set_nak_out_mreg_t set_nak_out_0;
    usbdev_reg2hw_set_nak_out_mreg_t set_nak_out_1;
    usbdev_reg2hw_set_nak_out_mreg_t set_nak_out_2;
    usbdev_reg2hw_in_sent_mreg_t in_sent_0;
    usbdev_reg2hw_in_sent_mreg_t in_sent_1;
    usbdev_reg2hw_in_sent_mreg_t in_sent_2;
    usbdev_reg2hw_out_stall_mreg_t out_stall_0;
    usbdev_reg2hw_out_stall_mreg_t out_stall_1;
    usbdev_reg2hw_out_stall_mreg_t out_stall_2;
    usbdev_reg2hw_in_stall_mreg_t in_stall_0;
    usbdev_reg2hw_in_stall_mreg_t in_stall_1;
    usbdev_reg2hw_in_stall_mreg_t in_stall_2;
    usbdev_reg2hw_configin_mreg_t configin_0;
    usbdev_reg2hw_configin_mreg_t configin_1;
    usbdev_reg2hw_configin_mreg_t configin_2;
    //usbdev_reg2hw_out_iso_mreg_t [5:0] out_iso; // [169:158]
    //usbdev_reg2hw_in_iso_mreg_t [5:0] in_iso; // [157:146]
    usbdev_reg2hw_out_data_toggle_reg_t out_data_toggle; // [145:120]
    usbdev_reg2hw_in_data_toggle_reg_t in_data_toggle; // [119:94]
    usbdev_reg2hw_phy_pins_drive_reg_t phy_pins_drive; // [93:85]
    usbdev_reg2hw_phy_config_reg_t phy_config; // [84:79]
    usbdev_reg2hw_wake_control_reg_t wake_control; // [78:75]
    usbdev_reg2hw_fifo_ctrl_reg_t fifo_ctrl; // [74:69]
    usbdev_reg2hw_count_out_reg_t count_out; // [68:46]
    usbdev_reg2hw_count_in_reg_t count_in; // [45:25]
    usbdev_reg2hw_count_nodata_in_reg_t count_nodata_in; // [24:10]
    usbdev_reg2hw_count_errors_reg_t count_errors; // [9:0]
  } usbdev_reg2hw_t;

  // HW -> register type
   //reduced [11:0] t0 [5:0]
  typedef struct packed {
    usbdev_hw2reg_intr_state_reg_t intr_state; // [402:367]
    usbdev_hw2reg_usbctrl_reg_t usbctrl; // [366:359]
    usbdev_hw2reg_usbstat_reg_t usbstat; // [358:329]
    usbdev_hw2reg_rxfifo_reg_t rxfifo; // [328:312]
    usbdev_hw2reg_rxenable_out_mreg_t [2:0] rxenable_out; // [311:288]
    usbdev_hw2reg_in_sent_mreg_t [2:0] in_sent; // [287:264]
    usbdev_hw2reg_out_stall_mreg_t [2:0] out_stall; // [263:240]
    usbdev_hw2reg_in_stall_mreg_t [2:0] in_stall; // [239:216]
    usbdev_hw2reg_configin_mreg_t [2:0] configin; // [215:144]
    usbdev_hw2reg_out_data_toggle_reg_t out_data_toggle; // [143:120]
    usbdev_hw2reg_in_data_toggle_reg_t in_data_toggle; // [119:96]
    usbdev_hw2reg_phy_pins_sense_reg_t phy_pins_sense; // [95:87]
    usbdev_hw2reg_wake_events_reg_t wake_events; // [86:79]
    usbdev_hw2reg_count_out_reg_t count_out; // [78:55]
    usbdev_hw2reg_count_in_reg_t count_in; // [54:32]
    usbdev_hw2reg_count_nodata_in_reg_t count_nodata_in; // [31:12]
    usbdev_hw2reg_count_errors_reg_t count_errors; // [11:0]
  } usbdev_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] USBDEV_INTR_STATE_OFFSET = 12'h 0;
  parameter logic [BlockAw-1:0] USBDEV_INTR_ENABLE_OFFSET = 12'h 4;
  parameter logic [BlockAw-1:0] USBDEV_INTR_TEST_OFFSET = 12'h 8;
  parameter logic [BlockAw-1:0] USBDEV_USBCTRL_OFFSET = 12'h 10;
  parameter logic [BlockAw-1:0] USBDEV_EP_OUT_ENABLE_OFFSET = 12'h 14;
  parameter logic [BlockAw-1:0] USBDEV_EP_IN_ENABLE_OFFSET = 12'h 18;
  parameter logic [BlockAw-1:0] USBDEV_USBSTAT_OFFSET = 12'h 1c;
  parameter logic [BlockAw-1:0] USBDEV_AVOUTBUFFER_OFFSET = 12'h 20;
  parameter logic [BlockAw-1:0] USBDEV_AVSETUPBUFFER_OFFSET = 12'h 24;
  parameter logic [BlockAw-1:0] USBDEV_RXFIFO_OFFSET = 12'h 28;
  parameter logic [BlockAw-1:0] USBDEV_RXENABLE_SETUP_OFFSET = 12'h 2c;
  parameter logic [BlockAw-1:0] USBDEV_RXENABLE_OUT_OFFSET = 12'h 30;
  parameter logic [BlockAw-1:0] USBDEV_SET_NAK_OUT_OFFSET = 12'h 34;
  parameter logic [BlockAw-1:0] USBDEV_IN_SENT_OFFSET = 12'h 38;
  parameter logic [BlockAw-1:0] USBDEV_OUT_STALL_OFFSET = 12'h 3c;
  parameter logic [BlockAw-1:0] USBDEV_IN_STALL_OFFSET = 12'h 40;
  parameter logic [BlockAw-1:0] USBDEV_CONFIGIN_0_OFFSET = 12'h 44;
  parameter logic [BlockAw-1:0] USBDEV_CONFIGIN_1_OFFSET = 12'h 48;
  parameter logic [BlockAw-1:0] USBDEV_CONFIGIN_2_OFFSET = 12'h 4c;
  parameter logic [BlockAw-1:0] USBDEV_OUT_DATA_TOGGLE_OFFSET = 12'h 7c;
  parameter logic [BlockAw-1:0] USBDEV_IN_DATA_TOGGLE_OFFSET = 12'h 80;
  parameter logic [BlockAw-1:0] USBDEV_PHY_PINS_SENSE_OFFSET = 12'h 84;
  parameter logic [BlockAw-1:0] USBDEV_PHY_PINS_DRIVE_OFFSET = 12'h 88;
  parameter logic [BlockAw-1:0] USBDEV_PHY_CONFIG_OFFSET = 12'h 8c;
  parameter logic [BlockAw-1:0] USBDEV_WAKE_CONTROL_OFFSET = 12'h 90;
  parameter logic [BlockAw-1:0] USBDEV_WAKE_EVENTS_OFFSET = 12'h 94;
  parameter logic [BlockAw-1:0] USBDEV_FIFO_CTRL_OFFSET = 12'h 98;
  parameter logic [BlockAw-1:0] USBDEV_COUNT_OUT_OFFSET = 12'h 9c;
  parameter logic [BlockAw-1:0] USBDEV_COUNT_IN_OFFSET = 12'h a0;
  parameter logic [BlockAw-1:0] USBDEV_COUNT_NODATA_IN_OFFSET = 12'h a4;
  parameter logic [BlockAw-1:0] USBDEV_COUNT_ERRORS_OFFSET = 12'h a8;

  // Reset values for hwext registers and their fields
  parameter logic [17:0] USBDEV_INTR_TEST_RESVAL = 18'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_PKT_RECEIVED_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_PKT_SENT_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_DISCONNECTED_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_HOST_LOST_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_LINK_RESET_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_LINK_SUSPEND_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_LINK_RESUME_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_AV_OUT_EMPTY_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_RX_FULL_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_AV_OVERFLOW_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_LINK_IN_ERR_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_RX_CRC_ERR_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_RX_PID_ERR_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_RX_BITSTUFF_ERR_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_FRAME_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_POWERED_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_LINK_OUT_ERR_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_INTR_TEST_AV_SETUP_EMPTY_RESVAL = 1'h 0;
  parameter logic [31:0] USBDEV_USBSTAT_RESVAL = 32'h 80000000;
  parameter logic [0:0] USBDEV_USBSTAT_RX_EMPTY_RESVAL = 1'h 1;
  parameter logic [4:0] USBDEV_AVOUTBUFFER_RESVAL = 4'h 0;
  parameter logic [4:0] USBDEV_AVSETUPBUFFER_RESVAL = 4'h 0;
  parameter logic [23:0] USBDEV_RXFIFO_RESVAL = 24'h 0;
  parameter logic [27:0] USBDEV_OUT_DATA_TOGGLE_RESVAL = 28'h 0;
  parameter logic [27:0] USBDEV_IN_DATA_TOGGLE_RESVAL = 28'h 0;
  parameter logic [16:0] USBDEV_PHY_PINS_SENSE_RESVAL = 17'h 0;
  parameter logic [1:0] USBDEV_WAKE_CONTROL_RESVAL = 2'h 0;
  parameter logic [0:0] USBDEV_WAKE_CONTROL_SUSPEND_REQ_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_WAKE_CONTROL_WAKE_ACK_RESVAL = 1'h 0;
  parameter logic [31:0] USBDEV_COUNT_OUT_RESVAL = 32'h 0;
  parameter logic [7:0] USBDEV_COUNT_OUT_COUNT_RESVAL = 8'h 0;
  parameter logic [0:0] USBDEV_COUNT_OUT_DATATOG_OUT_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_OUT_DROP_RX_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_OUT_DROP_AVOUT_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_OUT_IGN_AVSETUP_RESVAL = 1'h 0;
  parameter logic [5:0] USBDEV_COUNT_OUT_ENDPOINTS_RESVAL = 6'h 0;
  parameter logic [0:0] USBDEV_COUNT_OUT_RST_RESVAL = 1'h 0;
  parameter logic [31:0] USBDEV_COUNT_IN_RESVAL = 32'h 0;
  parameter logic [7:0] USBDEV_COUNT_IN_COUNT_RESVAL = 8'h 0;
  parameter logic [0:0] USBDEV_COUNT_IN_NODATA_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_IN_NAK_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_IN_TIMEOUT_RESVAL = 1'h 0;
  parameter logic [5:0] USBDEV_COUNT_IN_ENDPOINTS_RESVAL = 6'h 0;
  parameter logic [0:0] USBDEV_COUNT_IN_RST_RESVAL = 1'h 0;
  parameter logic [31:0] USBDEV_COUNT_NODATA_IN_RESVAL = 32'h 0;
  parameter logic [7:0] USBDEV_COUNT_NODATA_IN_COUNT_RESVAL = 8'h 0;
  parameter logic [5:0] USBDEV_COUNT_NODATA_IN_ENDPOINTS_RESVAL = 6'h 0;
  parameter logic [0:0] USBDEV_COUNT_NODATA_IN_RST_RESVAL = 1'h 0;
  parameter logic [31:0] USBDEV_COUNT_ERRORS_RESVAL = 32'h 0;
  parameter logic [7:0] USBDEV_COUNT_ERRORS_COUNT_RESVAL = 8'h 0;
  parameter logic [0:0] USBDEV_COUNT_ERRORS_PID_INVALID_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_ERRORS_BITSTUFF_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_ERRORS_CRC16_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_ERRORS_CRC5_RESVAL = 1'h 0;
  parameter logic [0:0] USBDEV_COUNT_ERRORS_RST_RESVAL = 1'h 0;

  // Window parameters
  parameter logic [BlockAw-1:0] USBDEV_BUFFER_OFFSET = 12'h 800;

  // Register index
  typedef enum int {
    USBDEV_INTR_STATE,
    USBDEV_INTR_ENABLE,
    USBDEV_INTR_TEST,
    USBDEV_USBCTRL,
    USBDEV_EP_OUT_ENABLE,
    USBDEV_EP_IN_ENABLE,
    USBDEV_USBSTAT,
    USBDEV_AVOUTBUFFER,
    USBDEV_AVSETUPBUFFER,
    USBDEV_RXFIFO,
    USBDEV_RXENABLE_SETUP,
    USBDEV_RXENABLE_OUT,
    USBDEV_SET_NAK_OUT,
    USBDEV_IN_SENT,
    USBDEV_OUT_STALL,
    USBDEV_IN_STALL,
    USBDEV_CONFIGIN_0,
    USBDEV_CONFIGIN_1,
    USBDEV_CONFIGIN_2,
    USBDEV_OUT_DATA_TOGGLE,
    USBDEV_IN_DATA_TOGGLE,
    USBDEV_PHY_PINS_SENSE,
    USBDEV_PHY_PINS_DRIVE,
    USBDEV_PHY_CONFIG,
    USBDEV_WAKE_CONTROL,
    USBDEV_WAKE_EVENTS,
    USBDEV_FIFO_CTRL,
    USBDEV_COUNT_OUT,
    USBDEV_COUNT_IN,
    USBDEV_COUNT_NODATA_IN,
    USBDEV_COUNT_ERRORS
  } usbdev_id_e;

  //For Iverilog
  parameter logic [3:0] USBDEV_PERMIT_0  = 4'b0111; // USBDEV_INTR_STATE
  parameter logic [3:0] USBDEV_PERMIT_1  = 4'b0111; // USBDEV_INTR_ENABLE
  parameter logic [3:0] USBDEV_PERMIT_2  = 4'b0111; // USBDEV_INTR_TEST
  parameter logic [3:0] USBDEV_PERMIT_3  = 4'b0111; // USBDEV_USBCTRL
  parameter logic [3:0] USBDEV_PERMIT_4  = 4'b0011; // USBDEV_EP_OUT_ENABLE
  parameter logic [3:0] USBDEV_PERMIT_5  = 4'b0011; // USBDEV_EP_IN_ENABLE
  parameter logic [3:0] USBDEV_PERMIT_6  = 4'b1111; // USBDEV_USBSTAT
  parameter logic [3:0] USBDEV_PERMIT_7  = 4'b0001; // USBDEV_AVOUTBUFFER
  parameter logic [3:0] USBDEV_PERMIT_8  = 4'b0001; // USBDEV_AVSETUPBUFFER
  parameter logic [3:0] USBDEV_PERMIT_9  = 4'b0111; // USBDEV_RXFIFO
  parameter logic [3:0] USBDEV_PERMIT_10 = 4'b0011; // USBDEV_RXENABLE_SETUP
  parameter logic [3:0] USBDEV_PERMIT_11 = 4'b0011; // USBDEV_RXENABLE_OUT
  parameter logic [3:0] USBDEV_PERMIT_12 = 4'b0011; // USBDEV_SET_NAK_OUT
  parameter logic [3:0] USBDEV_PERMIT_13 = 4'b0011; // USBDEV_IN_SENT
  parameter logic [3:0] USBDEV_PERMIT_14 = 4'b0011; // USBDEV_OUT_STALL
  parameter logic [3:0] USBDEV_PERMIT_15 = 4'b0011; // USBDEV_IN_STALL
  parameter logic [3:0] USBDEV_PERMIT_16 = 4'b1111; // USBDEV_CONFIGIN_0
  parameter logic [3:0] USBDEV_PERMIT_17 = 4'b1111; // USBDEV_CONFIGIN_1
  parameter logic [3:0] USBDEV_PERMIT_18 = 4'b1111; // USBDEV_CONFIGIN_2
  parameter logic [3:0] USBDEV_PERMIT_19 = 4'b1111; // USBDEV_OUT_DATA_TOGGLE
  parameter logic [3:0] USBDEV_PERMIT_20 = 4'b1111; // USBDEV_IN_DATA_TOGGLE
  parameter logic [3:0] USBDEV_PERMIT_21 = 4'b0111; // USBDEV_PHY_PINS_SENSE
  parameter logic [3:0] USBDEV_PERMIT_22 = 4'b0111; // USBDEV_PHY_PINS_DRIVE
  parameter logic [3:0] USBDEV_PERMIT_23 = 4'b0001; // USBDEV_PHY_CONFIG
  parameter logic [3:0] USBDEV_PERMIT_24 = 4'b0001; // USBDEV_WAKE_CONTROL
  parameter logic [3:0] USBDEV_PERMIT_25 = 4'b0011; // USBDEV_WAKE_EVENTS
  parameter logic [3:0] USBDEV_PERMIT_26 = 4'b0001; // USBDEV_FIFO_CTRL
  parameter logic [3:0] USBDEV_PERMIT_27 = 4'b1111; // USBDEV_COUNT_OUT
  parameter logic [3:0] USBDEV_PERMIT_28 = 4'b1111; // USBDEV_COUNT_IN
  parameter logic [3:0] USBDEV_PERMIT_29 = 4'b1111; // USBDEV_COUNT_NODATA_IN
  parameter logic [3:0] USBDEV_PERMIT_30 = 4'b1111; // USBDEV_COUNT_ERRORS

endpackage
